---
- name: Playbook to display Switch IP Address
  hosts: arista_switches
  gather_facts: no
  connection: network_cli
  become: yes
  become_method: enable

  vars:
    ansible_ssh_pass: alta3

  tasks:
    - name: run show interface on arista switches
      arista.eos.eos_command:
        commands:
          - show interfaces
      register: results

    - name: Print IP Address of switch
      debug:
        var: results.stdout_lines[0][2]
