---
- name: Network Agnostic Playbook
  hosts: aristaswitchessecure
  gather_facts: no

  vars:
    ansible_ssh_pass: alta3
    dnsserver: "8.8.8.8"

  tasks:
    - name: CONFIGURE DNS
      cli_config:
        config: ip name-server {{ dnsserver }}

    - name: CHECK CONFIG
      cli_command:
        command: show run | in ip name-server
      register: results

    - name: Print output to screen
      debug:
        var: results.stdout
        verbosity: 1

    - name: Check set_fact
      set_fact:
        expected_output: "ip name-server vrf default {{ dnsserver }}"

    - name: Check FAIL module
      fail:
        msg: failing 
      when: expected_output not in results.stdout


