---
- name: Playbook with the register keyword
  hosts: planetexpress

  tasks:
    - name: "Issue a trivial command"
      ansible.builtin.command: ls /lib/
      register: contentz_lib

    - name: "Debug - display data returned"
      ansible.builtin.debug:
        msg: "{{ contentz_lib }}"

    - name: "Debug - standard error"
      ansible.builtin.debug:
        msg: "{{ contentz_lib.stderr }}"

    - name: "Debug - standard out"
      ansible.builtin.debug:
        msg: "{{ contentz_lib.stdout }}"
 
