---
- name: Debug Loops with lists
  hosts: localhost
  gather_facts: false

  vars:
    my_list:
    - "1) A hyphen represents an item on a list"
    - "2) So the second item on the list is this"
    - "3) Whereas this would be the third"
    - "list 1 - item 4"

  tasks:
   - name: "Learning about the debug module"
     debug:
       msg: "Debug module allows us to print to the screen --> {{ item }}"
     loop: "{{ my_list }}"

